### ISSUE TITLE
Station can't see AP in scan results, if both of them use same 8852AU dongle

### ISSUE THREAD

**Issue by dmitttri** [shiqishao/RTL8852AU_WiFi_linux_v1.15.0.1-0-g487ee886.20210714#2]
Hi Shiqishao,
I have cloned driver source codes, compiled and deployed to my Linux machines. One machine runs as AP, the other stuarts in Station mode. Both machines uses the same 8852AU dongle, which is D-Link DWA-X1850.

The issue is that Station can't see AP in the Scan results, while it can see all other available AP's. I had the exact same issue with 8821au and 88x2bu chipsets. Just recently, Realtek published new versions of these drivers, under 20210708 release, and with 8821au and 88x2bu, the issue was solved.

I am wondering do you have access to the latest Realtek sources for 8852AU chipsets, if they had some recent release, this isse may be already solved. My only alternative right now is to make a complete cocde diif for 8821au, between the previous release (with this issue) and tha latest one (issue solved), and try to figure out which low level settings (register values) may affect this behavior. But only if Realtek don't have any recent releases, than this one you've kindly provided here.

I am also wondering, do I have to be in some kind of Realtek partner program, to gain access to Realtek Linux drivers sources?

Thanks in advance!
Dimitrije

**Comment by shiqishao** [comment]
Sorry, I can't solve your issue. These codes were leaked from another vendor instead of Realtek.
